// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CompositionComponent: typeof import('./src/components/CompositionComponent.vue')['default']
    EssentialLink: typeof import('./src/components/EssentialLink.vue')['default']
    README: typeof import('./src/components/README.md')['default']
  }
}

export { }
